# Generated by Django 4.2.17 on 2025-02-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteremployee',
            name='employee_type',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
