# Generated by Django 4.2.17 on 2025-02-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_masteremployee_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteremployee',
            name='employee_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
