# Generated by Django 4.2.17 on 2025-01-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_profile_branch_profile_bio_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(default='AIML', max_length=100),
        ),
    ]
