# Generated by Django 4.2.17 on 2025-02-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_masteremployee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='affil_status',
            field=models.CharField(choices=[('Affiliated', 'Affiliated'), ('Autonomous', 'Autonomous')], default='Affiliated', max_length=20),
        ),
        migrations.AlterField(
            model_name='semester',
            name='sem_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='university',
            name='affil_status',
            field=models.CharField(choices=[('Affiliated', 'Affiliated'), ('Autonomous', 'Autonomous')], default='Affiliated', max_length=20),
        ),
        migrations.AlterField(
            model_name='university',
            name='uni_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Deemed', 'Deemed')], default='Public', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('other', 'Other')], default='student', max_length=20),
        ),
    ]
