# Generated by Django 4.2.17 on 2025-01-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(choices=[('AIML', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('ChE', 'Chemical Engineering'), ('BME', 'Biomedical Engineering')], default='AIML', max_length=100),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
