# Generated by Django 4.2.17 on 2025-01-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
