# Generated by Django 4.2.17 on 2025-01-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_userotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
    ]
