# Generated by Django 4.2.17 on 2025-01-16 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_profile_branch_remove_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterstudent',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
