# Generated by Django 4.2.17 on 2025-01-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_masterstudent_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterstudent',
            old_name='user_username',
            new_name='user',
        ),
    ]
