# Generated by Django 4.2.17 on 2025-01-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aadhar_card_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
