# Generated by Django 4.2.17 on 2025-01-25 01:12

from django.db import migrations, models
import django.db.models.deletion

def set_default_branch(apps, schema_editor):
    MasterStudent = apps.get_model('myapp', 'MasterStudent')
    Branch = apps.get_model('myapp', 'Branch')
    default_branch = Branch.objects.first()
    for student in MasterStudent.objects.all():
        student.branch = default_branch
        student.save()

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_profile_aadhar_card_number_profile_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master_employees', to='myapp.department'),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='teaching_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterstudent',
            name='admission_year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='masterstudent',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_departments', to='myapp.department'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='myapp.institute')),
            ],
        ),
        migrations.AddField(
            model_name='institute',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutes', to='myapp.university'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='myapp.program')),
            ],
        ),
        migrations.AddField(
            model_name='masterstudent',
            name='branch',
            field=models.ForeignKey(on_delete=models.CASCADE, to='myapp.Branch'),
        ),
        migrations.AddField(
            model_name='masterstudent',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='myapp.institute'),
        ),
        migrations.AddField(
            model_name='masterstudent',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='myapp.program'),
        ),
        migrations.AddField(
            model_name='masterstudent',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='myapp.university'),
        ),
    ]
