# Generated by Django 4.2.17 on 2025-01-25 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_masterstudent_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='program',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.AddField(
            model_name='branch',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='myapp.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='myapp.program'),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='employee_id',
            field=models.CharField(default='default_employee_id', max_length=20),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='employee_type',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='institute',
            field=models.ForeignKey(default= 1, on_delete=django.db.models.deletion.CASCADE, to='myapp.institute'),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='position',
            field=models.CharField(default='employee', max_length=100),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.program'),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.university'),
        ),
        migrations.AddField(
            model_name='masterstudent',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AddField(
            model_name='masterstudent',
            name='student_id',
            field=models.CharField(default='default_student_id', max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='masteremployee',
            name='department',
            field=models.ForeignKey(default='cse', on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='masteremployee',
            name='teaching_subject',
            field=models.CharField(blank=True, default='python', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masteremployee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.branch'),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.institute'),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.program'),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.university'),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
