# Generated by Django 4.2.17 on 2025-01-25 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_branch_program_remove_department_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteremployee',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='masteremployee',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.institute'),
        ),
        migrations.AlterField(
            model_name='masteremployee',
            name='program',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.program'),
        ),
        migrations.AlterField(
            model_name='masteremployee',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.university'),
        ),
        migrations.AlterField(
            model_name='masteremployee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
