# Generated by Django 4.2.17 on 2025-01-25 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_branch_department_alter_department_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteremployee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='masteremployee',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.institute'),
        ),
        migrations.AlterField(
            model_name='masteremployee',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.program'),
        ),
        migrations.AlterField(
            model_name='masteremployee',
            name='teaching_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masteremployee',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.university'),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.branch'),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.institute'),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.program'),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.university'),
        ),
    ]
