# Generated by Django 4.2.17 on 2025-01-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_masteremployee_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masteremployee',
            name='position',
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='approval_authority',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='assigned_counters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='assigned_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='classes_grades_assigned',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='coordinating_departments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='department_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='handled_payment_modes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='key_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='scholarship_programs_managed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='software_tools_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='special_skills_certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='staff_supervised',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='subjects_taught',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='teaching_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='work_schedule_shift_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masteremployee',
            name='years_of_experience_in_institution',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
