# Generated by Django 4.2.17 on 2025-01-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_masteremployee_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterstudent',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
